ADAPTER_KIND = "ManagementPackforOmnissaMultiPods"
ADAPTER_NAME = "Management Pack for Omnissa Multi Pods"
HOST_IDENTIFIER = "host"
PORT_IDENTIFIER = "port"
USER_CREDENTIAL = "user"
PASSWORD_CREDENTIAL = "password"
DOMAIN_CREDENTIAL = "domain"
