ADAPTER_KIND = "OmnissaMultiPods"
ADAPTER_NAME = "Omnissa Multi Pods for Altice"
HOST_IDENTIFIER = "host"
PORT_IDENTIFIER = "port"
USER_CREDENTIAL = "user"
PASSWORD_CREDENTIAL = "password"
DOMAIN_CREDENTIAL = "domain"